### ISSUE TITLE
Infinite scanning

### ISSUE THREAD

**Issue by apocrf** [maniacx/Airpods-Battery-Monitor#16]
Hi! Thank you very much for that extension, its relly look perfect! Unfortunatelly i cant get battery info and get infinite scanning. I have already check my  `/etc/bluetooth/main.conf` and uncomment dual mode line just in case. Tried to restart gnome and reboot, nothing helps. Can you please hint me where is the problem?

![image](https://github.com/maniacx/Airpod-Battery-Monitor/assets/15089121/cb64c01b-17eb-46f2-935b-90d4e3ed02f5)

**Comment by maniacx** [comment]
* Disable the extension

* If you have opened Gnome settings close that too.

* Make sure air pods are on and out of case

* Run test.js https://maniacx.github.io/Airpod-Battery-Monitor/bugs-feature-request#script-for-getting-manufacturer-data
Wait for a minute. If it post manufacturer data and battery info post it here.

* If test.js doesn't post any output. Try step number 5 in Bugs debudding document https://maniacx.github.io/Airpod-Battery-Monitor/bugs-feature-request#bugs-and-debugging
Follow this instruction and see if it scans airpods

**Comment by maniacx** [comment]
Also make sure you have selected correct air pods model in Extension preference

**Comment by apocrf** [comment]
> Also make sure you have selected correct air pods model in Extension preference

I started with that and realised that i mixed up my airpods model. Everything works great now! Thank you again for great extension!
